name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm-ci
        run: npm ci
      # Runs the Super-Linter action
      - name: Run Lint
        run: npm run lint

      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{secrets.APP_NAME}}" #Must be unique in Heroku
          heroku_email: "guiihpr@gmail.com"